# Generated by Django 3.2.9 on 2021-12-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(default='', max_length=128, verbose_name='md5值')),
                ('chunk_number', models.IntegerField(default=-1, verbose_name='第几个分片')),
                ('name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('path', models.CharField(max_length=255, verbose_name='路径')),
                ('check_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校验文件信息',
            },
        ),
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文件名称')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('md5', models.CharField(default='', max_length=255, verbose_name='md5值')),
                ('size', models.CharField(default=0, max_length=32, verbose_name='文件大小')),
                ('upload_finish', models.BooleanField(default=False, verbose_name='文件是否完整生成完成')),
                ('total_chunks', models.IntegerField(verbose_name='总的分片数')),
                ('path', models.CharField(max_length=255, verbose_name='完整文件存放路径')),
                ('chunk_path', models.CharField(max_length=255, verbose_name='分片文件存放路径')),
            ],
            options={
                'verbose_name': '上传文件信息',
            },
        ),
    ]
